# Site settings
title: "<murder>violent</murder>"
description: "Diam coding, berbicara seperlunya, menulis sesukanya"
baseurl: "" # begin with /repo-name if use as project, else leave empty for gh-pages
url: "" # default is empty
author: "Naufaltrix | Gol D Fals"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave empty to disable it
google_analytics:
disqus_shortname: hnbloggithub
